# Generated by Django 4.0.7 on 2026-02-23 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='news.event')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_report',
            },
        ),
        migrations.AddIndex(
            model_name='eventreport',
            index=models.Index(fields=['event', 'created_at'], name='event_repor_event_i_e6fc09_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreport',
            index=models.Index(fields=['reported_by'], name='event_repor_reporte_9431f2_idx'),
        ),
    ]
