# Generated by Django 4.0.7 on 2026-02-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_eventreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreport',
            name='event',
            field=models.BigIntegerField(db_column='event_id', db_index=True),
        ),
        migrations.AlterField(
            model_name='eventreport',
            name='reported_by',
            field=models.BigIntegerField(db_column='reported_by_id', db_index=True),
        ),
    ]
