# Generated by Django 4.0.7 on 2026-02-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_eventreport_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('author_id', models.BigIntegerField(db_index=True)),
                ('reply_to', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_comment',
            },
        ),
        migrations.AddIndex(
            model_name='eventcomment',
            index=models.Index(fields=['event_id', 'created_at'], name='event_comme_event_i_72cbde_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcomment',
            index=models.Index(fields=['reply_to', 'created_at'], name='event_comme_reply_t_624a46_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcomment',
            index=models.Index(fields=['status'], name='event_comme_status_a837e1_idx'),
        ),
    ]
