# Generated by Django 4.0.7 on 2026-02-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_eventcomment_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventcomment',
            name='event_comme_reply_t_624a46_idx',
        ),
        migrations.RemoveField(
            model_name='eventcomment',
            name='reply_to',
        ),
    ]
