# Generated by Django 4.0.7 on 2026-02-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_eventcomment_event_comme_reply_t_624a46_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='source_logos/'),
        ),
    ]
