# Generated by Django 4.0.7 on 2026-02-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_source_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('target_type', models.CharField(choices=[('event', 'Event'), ('story', 'Story'), ('person', 'Person'), ('source', 'Source'), ('entity', 'Entity')], db_index=True, max_length=20)),
                ('target_id', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'follow',
            },
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['target_type', 'target_id'], name='follow_target__e696e9_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['user_id', 'created_at'], name='follow_user_id_41e371_idx'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user_id', 'target_type', 'target_id'), name='follow_user_target_type_target_id_uniq'),
        ),
    ]
